name: wallet
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.1.0
  country_code_picker: ^3.3.0
  rxdart: ^0.28.0
  provider: ^6.1.5
  flutter_otp_text_field: ^1.5.1+1
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5
  intl: ^0.20.2
  sliver_tools: ^0.2.12

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  freezed: ^2.5.7
  build_runner: ^2.5.1
  json_serializable: ^6.9.0
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/svgs/
    - assets/images/
